server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/fooddb
spring.datasource.username=root
spring.datasource.password=manya@23

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true